Issue #318 - support datetime-tz
ppodgorsek/docker-robot-framework pull request #319
Opened 2020-12-11 03:27 UTC by UltimateDogg

2020-12-11 14:59 UTC, ppodgorsek requested changes
The PR looks good, I would however suggest adding automated tests and an explanation in the README about how it works.

2020-12-11 15:10 UTC, ppodgorsek commented
Would it be possible to define the timezone as an environment variable? (by default, UTC) When running it, users could simply pass a new variable value instead of any complex setup.
This would probably require additional changes in the launch script.

2020-12-11 15:19 UTC, UltimateDogg commented
> 
> 
> Would it be possible to define the timezone as an environment variable? (by default, UTC) When running it, users could simply pass a new variable value instead of any complex setup.
> This would probably require additional changes in the launch script.

yes timezones are everywhere, and i am not familiar with everything wed have to change. But this library at least makes it so you can account for differences between local time (UTC in this image) and the website you are on.

2020-12-18 20:04 UTC, ppodgorsek requested changes

2020-12-18 20:04 UTC, ppodgorsek commented on README.md
> +To set the timezone used inside the docker image, you can set env variable TZ
```suggestion
To set the timezone used inside the Docker image, you can set the `TZ` environment variable:
```

2020-12-18 20:04 UTC, ppodgorsek commented on README.md
> +This project is meant to allow your tests to run anywhere. Sometimes that can be in a different timezone than your local or the location under test. To help with that this library includes the [DateT
```suggestion
This project is meant to allow your tests to run anywhere. Sometimes that can be in a different timezone than your local one or of the location under test. To help solve such issues, this image includes the [DateTimeTZ Library](https://testautomation.github.io/DateTimeTZ/doc/DateTimeTZ.html).
```

2020-12-18 20:05 UTC, ppodgorsek approved these changes

2020-12-18 20:15 UTC, merged