Add axe selenium library
ppodgorsek/docker-robot-framework pull request #328
Opened 2021-02-10 23:40 UTC by rkefi84

We use the axe selenium library for our automated accessibility tests, and would be nice to have it included.

Here is a link for the library : https://github.com/mozilla-services/axe-selenium-python

Thanks!

2021-02-11 00:10 UTC, rkefi84 commented
Build Image step failing with this error :
```
ERROR: Could not build wheels for cryptography which use PEP 517 and cannot be installed directly
WARNING: You are using pip version 20.3.1; however, version 21.0.1 is available.
```
Getting the same error when i tried locally without the axe library too and got the same

2021-02-16 18:22 UTC, UltimateDogg requested changes

2021-02-16 18:22 UTC, UltimateDogg commented on Dockerfile
> +    axe-selenium-python \
please tag to a version like the other libraries

2021-02-16 18:22 UTC, UltimateDogg commented
> 
> 
> Build Image step failing with this error :
> 
> ```
> ERROR: Could not build wheels for cryptography which use PEP 517 and cannot be installed directly
> WARNING: You are using pip version 20.3.1; however, version 21.0.1 is available.
> ```
> 
> Getting the same error when i tried locally without the axe library too and got the same

It seems there is some rust dependency we need now, that will be fixed in another pull

2021-02-24 19:29 UTC, ppodgorsek commented on README.md
> +* [Axe Selenium Library](https://github.com/mozilla-services/axe-selenium-python) 2.6.1
The latest release is 2.1.6

2021-02-24 19:32 UTC, ppodgorsek requested changes

2021-02-24 19:32 UTC, ppodgorsek commented on Dockerfile
> +    axe-selenium-python \
```suggestion
    axe-selenium-python==$AXE_SELENIUM_LIBRARY_VERSION \
```

2021-02-24 19:34 UTC, ppodgorsek approved these changes

2021-02-24 20:55 UTC, merged