add Rust as dependencies for cryptography, add XLS support for data d…
ppodgorsek/docker-robot-framework pull request #332
Opened 2021-02-16 23:58 UTC by linh-ngophuochoai

Fix dependency issue for cryptography due to Rust
Add XLS support for Data Driver

2021-02-17 01:20 UTC, UltimateDogg commented
Can you leave the existing whitesapce?

2021-02-17 01:56 UTC, linh-ngophuochoai commented
Hi, I am not so sure what does it mean by whitespace. I believe it related to CRLF as I am using Windows machine. Converted to LF and add some comment. Hope it helps

2021-02-19 20:54 UTC, ppodgorsek requested changes
As @UltimateDogg pointed out, there was no need to change so many lines, whitespace must be consistent.
Please see for yourself in the "Files changed" tab at the top of this PR.

2021-02-19 21:00 UTC, ppodgorsek requested changes

2021-02-19 21:00 UTC, ppodgorsek commented on Dockerfile
> +  wget \
```suggestion

    # Install dependencies for cryptography due to https://github.com/pyca/cryptography/issues/5771
    cargo \
    rust \

    # Continue with system dependencies
    gcc \
    g++ \
    libffi-dev \
    linux-headers \
    make \
    musl-dev \
    openssl-dev \
    which \
    wget \
```

2021-02-19 21:02 UTC, ppodgorsek commented on Dockerfile
> +  # Clean up buildtime dependencies
```suggestion
# Clean up buildtime dependencies
```

2021-02-19 21:03 UTC, UltimateDogg approved these changes

2021-02-19 21:46 UTC, ppodgorsek approved these changes

2021-02-19 22:02 UTC, merged