Updated Robot framework and Pabot library version
ppodgorsek/docker-robot-framework pull request #429
Opened 2023-03-22 01:41 UTC by rs-roy

Updated Robot framework version from 5.0.1 to 6.0.2 and Pabot library from version 2.7.0 to 2.14.0

2023-05-08 13:19 UTC, cas-technology approved these changes

2023-05-09 12:54 UTC, ppodgorsek requested changes
Thank you very much for your contribution!
I added a comment about the Pabot version. Could you also update the versions listed in the README please?

2023-05-09 12:54 UTC, ppodgorsek commented on Dockerfile
> +ENV PABOT_VERSION 2.14.0
Latest version is 2.15.0

2023-05-11 09:38 UTC, rs-roy commented
Updated to robotframework, pabot and seleniumlibrary to the latest version in Dockerfile and mentioned in the README

2023-05-24 08:56 UTC, ppodgorsek approved these changes

2023-05-24 08:57 UTC, merged